model:
  arch: blip2_qformer
  model_type: pretrain
  config:
    config:
      vision_config:
        hidden_size: 1408
        intermediate_size: 6144
        num_hidden_layers: 39
        num_attention_heads: 16
        image_size: 224
        patch_size: 14
        hidden_act: gelu
        layer_norm_eps: 0.00001
        attention_dropout: 0.0
        initializer_range: 1e-10
        qkv_bias: True
      qformer_config:
        vocab_size: 30522
        hidden_size: 768
        num_hidden_layers: 12
        num_attention_heads: 12
        intermediate_size: 3072
        hidden_act: "gelu"
        hidden_dropout_prob: 0.1
        attention_probs_dropout_prob: 0.1
        max_position_embeddings: 512
        initializer_range: 0.02
        layer_norm_eps: 1e-12
        pad_token_id: 0
        position_embedding_type: "absolute"
        cross_attention_frequency: 2
        encoder_hidden_size: 1408
    num_query_tokens: 32
    tokenizer_pretrained_path: /code-online/code/resources/models/bert-base-uncased
    vision_pretrain_path: /code-online/code/resources/models/blip2-vision-model/blip2_vision_model.pth



datasets:
  coco_caption:
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
  vg_caption: # name of the dataset builder
    vis_processor:
      train:
        name: "blip_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  learning_rate: 1e-4
  min_lr: 1e-5
  warmup_lr: 1e-6

  weight_decay: 0.05
  num_train_epochs: 10
  per_device_train_batch_size: 100
  per_device_eval_batch_size: 64
  num_workers: 4
  warmup_steps: 5000

  seed: 42
  output_dir: "output/BLIP2/Pretrain_stage1"
  overwrite_output_dir: False

  amp: True
  resume_ckpt_path: null

  do_train: True
  do_eval: False
  save_strategy: steps

  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True